# Generated by Django 4.0.5 on 2022-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comAPI', '0003_remove_category_owner_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='categories', to='comAPI.post'),
        ),
    ]
