# Generated by Django 4.0.5 on 2022-06-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comAPI', '0006_alter_comment_options_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
